Update tools.py
Original code causes:
~/faceswap$ python tools.py --help
Please backup your data and/or test the tool you want to use with a smaller data set to make sure you understand how it works.
tools.py
Traceback (most recent call last):
  File "tools.py", line 33, in <module>
    gui = TKGui(
NameError: name 'TKGui' is not defined